from django.contrib import admin
from exerciser.models import Document, Fragment, Step, Change, Explanation, Question, Option, Application, Panel, UsageRecord, QuestionRecord, Group, Teacher, Student, AcademicYear, FragmentStyle
admin.site.register(Document)
admin.site.register(Fragment)
admin.site.register(Step)
admin.site.register(Change)
admin.site.register(Explanation)
admin.site.register(Question)
admin.site.register(Option)
admin.site.register(Application)
admin.site.register(Panel)
admin.site.register(UsageRecord)
admin.site.register(QuestionRecord)
admin.site.register(Group)
admin.site.register(Teacher)
admin.site.register(Student)
admin.site.register(AcademicYear)
admin.site.register(FragmentStyle)